# Generated by Django 4.2.15 on 2026-03-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ancestor",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_as_father",
                to="heritage.ancestor",
            ),
        ),
        migrations.AddField(
            model_name="ancestor",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_as_mother",
                to="heritage.ancestor",
            ),
        ),
        migrations.AddField(
            model_name="ancestor",
            name="spouses",
            field=models.ManyToManyField(blank=True, to="heritage.ancestor"),
        ),
    ]
