# Generated by Django 4.2.15 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceenrollment',
            name='embedding_model',
            field=models.CharField(default='Facenet', help_text='Model used to generate embeddings', max_length=50),
        ),
        migrations.AddField(
            model_name='faceenrollment',
            name='embeddings',
            field=models.JSONField(default=list, help_text='List of base64-encoded face embeddings'),
        ),
        migrations.AlterField(
            model_name='faceenrollment',
            name='face_ids',
            field=models.JSONField(default=list, help_text='Legacy AWS Rekognition face IDs (deprecated)'),
        ),
        migrations.AlterField(
            model_name='tagsuggestion',
            name='aws_face_id',
            field=models.CharField(blank=True, help_text='Legacy AWS face ID (deprecated)', max_length=100, null=True),
        ),
    ]
