import os
import sys
import django

def fix_heritage_tables():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api.settings')
    django.setup()
    
    from django.db import connection
    
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT 1 FROM heritage_ancestor LIMIT 1;")
            print("Heritage tables already exist.")
            return
        except Exception:
            print("Heritage tables missing! Creating via raw SQL...")
            connection.rollback()
            
            sql = """
            CREATE TABLE IF NOT EXISTS "heritage_ancestor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "unique_id" varchar(100) NOT NULL, "name" varchar(200) NOT NULL, "relation" varchar(100) NOT NULL, "gender" varchar(10) NOT NULL, "birth_date" date NULL, "birth_year" integer NULL, "death_date" date NULL, "death_year" integer NULL, "origin" varchar(200) NOT NULL, "source_type" varchar(20) NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_heritagelocation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "original_name" varchar(200) NOT NULL, "latitude" double precision NULL, "longitude" double precision NULL, "location_type" varchar(50) NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_heritagemedia" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "file" varchar(100) NOT NULL, "media_type" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "user_id" integer NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_userprofile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "first_name" varchar(100) NOT NULL, "last_name" varchar(100) NOT NULL, "access_level" varchar(20) NOT NULL, "interview_completed" boolean NOT NULL, "interview_started_at" timestamp with time zone NULL, "interview_completed_at" timestamp with time zone NULL, "json_backup_url" varchar(200) NULL, "user_id" integer NOT NULL UNIQUE);
            CREATE TABLE IF NOT EXISTS "heritage_story" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "content" text NOT NULL, "context" varchar(200) NOT NULL, "ancestor_id" bigint NOT NULL, "user_id" integer NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_mediatag" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "box_x" double precision NOT NULL, "box_y" double precision NOT NULL, "ancestor_id" bigint NOT NULL, "media_id" bigint NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_importbatch" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "filename" varchar(200) NOT NULL, "uploaded_at" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "user_id" integer NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_heritageevent" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NOT NULL, "date_start" date NULL, "date_end" date NULL, "event_type" varchar(20) NOT NULL, "location_id" bigint NULL);
            CREATE TABLE IF NOT EXISTS "heritage_eventparticipation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role" varchar(100) NOT NULL, "ancestor_id" bigint NOT NULL, "event_id" bigint NOT NULL);
            CREATE TABLE IF NOT EXISTS "heritage_ancestorfact" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(100) NOT NULL, "value" text NOT NULL, "ancestor_id" bigint NOT NULL);

            ALTER TABLE "heritage_ancestor" ADD COLUMN IF NOT EXISTS "birth_location_id" bigint NULL;
            ALTER TABLE "heritage_ancestor" ADD COLUMN IF NOT EXISTS "import_batch_id" bigint NULL;
            ALTER TABLE "heritage_ancestor" ADD COLUMN IF NOT EXISTS "user_id" integer NOT NULL;
            """
            
            for statement in sql.split(';'):
                if statement.strip():
                    try:
                        cursor.execute(statement)
                    except Exception as e:
                        print(f"Warning on execution: {e}")
                        connection.rollback()
                        
            # Insert the migration record if not exists so Django is happy
            cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES ('heritage', '0001_initial', CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;")
            print("Heritage tables created!")

if __name__ == "__main__":
    fix_heritage_tables()
