import os
import sys
import django

def fix_heritage_tables():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api.settings')
    django.setup()
    
    from django.db import connection
    
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT 1 FROM heritage_userprofile LIMIT 1;")
            print("Table heritage_userprofile already exists.")
        except Exception:
            print("Table heritage_userprofile is missing. Creating it via raw SQL...")
            connection.rollback()  # Reset transaction after the failed SELECT
            
            # Create the specific missing table
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS "heritage_userprofile" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
                "first_name" varchar(100) NOT NULL, 
                "last_name" varchar(100) NOT NULL, 
                "access_level" varchar(20) NOT NULL, 
                "interview_completed" boolean NOT NULL, 
                "interview_started_at" timestamp with time zone NULL, 
                "interview_completed_at" timestamp with time zone NULL, 
                "json_backup_url" varchar(200) NULL, 
                "user_id" integer NOT NULL UNIQUE
            );
            """)
            print("Table heritage_userprofile created successfully!")

if __name__ == "__main__":
    fix_heritage_tables()
