# Generated by Django 4.2.15 on 2025-11-25 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ancestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        help_text="Unique identifier like 'bjorn_grandfather'",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "relation",
                    models.CharField(
                        help_text="Relationship to user (e.g., grandfather, aunt)",
                        max_length=100,
                    ),
                ),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("birth_place", models.CharField(blank=True, max_length=200)),
                ("origin", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("interview_completed", models.BooleanField(default=False)),
                ("interview_started_at", models.DateTimeField(blank=True, null=True)),
                ("interview_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "json_backup_url",
                    models.URLField(
                        blank=True, help_text="S3 URL of full JSON backup", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heritage_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                ("chat_history", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AncestorMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="ancestor_media/%Y/%m/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="questionaire.ancestor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "context",
                    models.CharField(
                        blank=True, help_text="Context of the story", max_length=200
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="questionaire.ancestor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="questionair_user_id_26fdf1_idx",
                    ),
                    models.Index(
                        fields=["ancestor", "-created_at"],
                        name="questionair_ancesto_50f4ae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AncestorFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Fact name (e.g., occupation, hair_color)",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField(help_text="Fact value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="questionaire.ancestor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ancestor", "key"],
                        name="questionair_ancesto_20e552_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ancestor",
            index=models.Index(
                fields=["user", "unique_id"], name="questionair_user_id_ca21b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ancestor",
            index=models.Index(
                fields=["user", "relation"], name="questionair_user_id_6c4c10_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ancestor",
            unique_together={("user", "unique_id")},
        ),
    ]
